/* Optional browser acceptance: uses an installed Playwright and isolated browser only.
   NODE_PATH=/path/to/node_modules BROWSER_EXECUTABLE=/path/to/chrome node tests/browser_trace_viewer.cjs FIXTURES OUTPUT
   Build fixtures first with .venv/bin/python tests/build_viewer_browser_fixtures.py FIXTURES. */
const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
(async () => {
  const fixtures = path.resolve(process.argv[2]), output = path.resolve(process.argv[3]);
  fs.mkdirSync(output, {recursive:true});
  const browser = await chromium.launch({headless:true, executablePath:process.env.BROWSER_EXECUTABLE});
  const context = await browser.newContext({viewport:{width:1450,height:1050}});
  const page = await context.newPage();
  const externalRequests=[], errors=[], checks=[];
  page.on('request', r=>{if(!r.url().startsWith('file:'))externalRequests.push(r.url());});
  page.on('pageerror', e=>errors.push(e.message));
  page.on('console', e=>{if(e.type()==='error')errors.push(e.text());});
  await context.route('**/*', route => route.request().url().startsWith('file:') ? route.continue() : route.abort());
  const open = async name => {
    await page.goto(pathToFileURL(path.join(fixtures,name+'.html')).href);
    assert.equal(await page.locator('#error').isVisible(),false,name);
  };
  const tab = name=>page.getByRole('tab',{name,exact:true}).click();
  await open('tools');
  assert.equal(await page.locator('.timeline-item').count(),10);
  assert.match(await page.locator('#overview').innerText(),/已标记发送\n6/);
  assert.match(await page.locator('#overview').innerText(),/工具调用\n4/);
  await page.locator('#kind-filter').selectOption('TOOL');
  assert.equal(await page.locator('.timeline-item').count(),4);
  await page.locator('.timeline-item').first().click();
  assert.match(await page.locator('#detail-content').innerText(),/unit.hunks/);
  await tab('请求');assert.match(await page.locator('#detail-content').innerText(),/source_request_ref/);
  await tab('回复 / 结果');assert.match(await page.locator('#detail-content').innerText(),/callers guarantee/);
  await tab('概览与关系');await page.getByRole('button',{name:'查看触发工具的模型调用',exact:true}).click();
  assert.equal(await page.locator('#kind-filter').inputValue(),'');
  assert.match(await page.locator('#selection-header').innerText(),/CALL \/ REVIEW/);
  checks.push('tool filter, parameters, result, source request and jump clearing filter');
  await page.locator('#kind-filter').selectOption('REPAIR');
  await page.locator('.timeline-item').click();
  assert.match(await page.locator('#detail-content').innerText(),/result_88370663f68063711192f0ef/);
  await tab('预算');assert.match(await page.locator('#detail-content').innerText(),/RESERVE/);
  await page.locator('#search').fill('no-such-call-content');
  assert.equal(await page.locator('.timeline-item').count(),0);
  checks.push('repair exact source result, budget and empty search');
  await open('retry');
  await page.locator('#status-filter').selectOption('UNKNOWN');
  await page.locator('.timeline-item').click();
  assert.match(await page.locator('#detail-content').innerText(),/BOUND/);
  await tab('预算');assert.match(await page.locator('#detail-content').innerText(),/600 \/ \$0.000800000/);
  assert.match(await page.locator('#overview').innerText(),/HELD · 任务级\n\$0.000800000/);
  checks.push('unknown retry decision and held not released or reset');
  await open('finding');
  await page.locator('.finding-card').click();
  assert.match(await page.locator('#selection-header').innerText(),/FINDING/);
  await tab('锚点与证据');
  const evidenceText=await page.locator('#detail-content').innerText();
  for(const role of ['评论锚点','支持证据','契约证据'])assert.ok(evidenceText.includes(role));
  assert.equal(await page.locator('.evidence-card').count(),5);
  await page.screenshot({path:path.join(output,'finding-evidence-desktop.png'),fullPage:true});
  await page.getByRole('button',{name:'查看证据所属调用',exact:true}).first().click();
  await tab('回复 / 结果');assert.match(await page.locator('#detail-content').innerText(),/ZeroDivisionError/);
  checks.push('finding original body, anchor/support/contract evidence and request jump');
  await open('repair');assert.equal(await page.locator('.timeline-item').count(),2);
  await page.locator('.finding-card').click();await tab('关联调用');
  await page.getByRole('button',{name:'查看所属模型调用',exact:true}).click();
  assert.match(await page.locator('#selection-header').innerText(),/CALL \/ REPAIR/);
  checks.push('finding belongs to repair attempt and nested source is deduplicated');
  await open('source');await page.locator('.meta-panel>summary').click();
  assert.match(await page.locator('#metadata').innerText(),/PYTHON_COMPLETE/);
  checks.push('source coverage in overview metadata');
  await open('partial');assert.equal(await page.locator('.timeline-item').count(),0);
  assert.match(await page.locator('#mode').innerText(),/部分审计区段/);
  assert.match(await page.locator('#overview').innerText(),/未提供/);
  checks.push('partial pricing trace keeps missing counts and task status unknown');
  await open('attack');await page.locator('.finding-card').click();
  assert.match(await page.locator('#selection-header').innerText(),/<script>/);
  await page.getByRole('button',{name:'查看所属请求、原回复与预算',exact:true}).click();
  await tab('回复 / 结果');assert.match(await page.locator('#detail-content').innerText(),/attacker.invalid/);
  assert.equal(await page.locator('img,a,iframe,object').count(),0);
  assert.equal(await page.evaluate(()=>globalThis.viewerPwned),undefined);
  assert.equal(await page.locator('script').count(),2);
  checks.push('script closing, img/onerror and javascript URL stay inert text');
  await open('unknown');assert.match(await page.locator('#detail-content').innerText(),/不会重试或释放 HELD/);
  checks.push('unknown status is not completed and zero findings are not zero defects');
  await page.setViewportSize({width:390,height:844});await open('finding');
  await page.locator('.finding-card').click();await tab('锚点与证据');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:path.join(output,'finding-evidence-mobile.png'),fullPage:true});
  checks.push('mobile layout has no horizontal overflow');
  assert.deepEqual(errors,[]);assert.deepEqual(externalRequests,[]);
  const result={mode:'offline_browser_acceptance',pages:8,checks,errors,externalRequests,modelCalls:0};
  fs.writeFileSync(path.join(output,'browser-results.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});
  console.log(JSON.stringify(result));await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
